FROM python:3.7.5-buster

LABEL maintainer "JongHwa Kim"

ENV APP_PATH /home/docker

COPY AWS_IAM.py $APP_PATH/

COPY output.txt $APP_PATH/

WORKDIR /home/docker

#CMD ["python3", "/home/docker/AWS_IAM.py", "320"]
